/*
* @purpose: This is the exception class which will raise any custom exception.
* @author:  Cloud Consulting Group GmbH
* @email:   support@cloudconsulting24.com
*
* @history:
* version                   | author                       | changes
* ====================================================================================
* 1.0 (04-05-2018)          | Cloud Consulting Group GmbH  | initial version
*/
public class DoiException extends Exception{
    
}